SUBDIRS = bin src

compile:
		@echo "*** Compiling all in `pwd`"
		@for dir in $(SUBDIRS); do \
		  (cd $$dir ; make -f Makefile.linux compile) \
		done


clean:
		@echo "*** Cleaning `pwd`"
		@for dir in $(SUBDIRS); do \
		  (cd $$dir ; make -f Makefile.linux clean) \
		done
