#ifndef _daeErrors_INCLUDE_
#define _daeErrors_INCLUDE_


// fatal conditons (generated by m4)
define(`FATALMSG',`#define' $1 $2)
pushdef(`ERRORMSG')
pushdef(`WARNINGMSG')
include(daeErrors.msg)

// error conditions (generated by m4)
define(`FATALMSG')
define(`ERRORMSG',`#define' $1 $2)
define(`WARNINGMSG')
include(daeErrors.msg)

// warning conditions (generated by m4)
pushdef(`FATALMSG')
pushdef(`ERRORMSG')
pushdef(`WARNINGMSG',`#define' $1 $2)
include(daeErrors.msg)


// fatal call 
#define fatal(i)                     _fatal( __LINE__, __FILE__, (i) )


extern int  numErrors;

extern void _fatal( int, const char *, int );
extern void error( int, ... );
extern void warning( int, ... );

void insertError( const char * );
void insertFmtError( const char *, ... );
void printErrors( FILE *file );


#endif /* _daeErrors_INCLUDE_ */
